Issue2 user can view entries
omidzed/code-journal pull request #6
Opened 2023-09-25 04:47 UTC by omidzed

No screenshot. Will send you a video clip upon request.

2023-09-25 05:03 UTC, shawnkost requested changes
Some changes here Omid!

2023-09-25 05:03 UTC, shawnkost commented on js/main.js
> +}
`toggleNoEntries` should be checking if `data.entries.length` has anything. If it does, then you would just query for the element with the "No entries" text, and give it a class of `hidden`, or you would remove it. It shouldn't be an entirely different view

2023-09-28 17:25 UTC, shawnkost requested changes
Few changes here Omid!

2023-09-28 17:25 UTC, shawnkost commented on index.html
> +            <!-- <div class=" entry-form"> -->
Delete all old code

2023-09-28 17:25 UTC, shawnkost commented on js/main.js
> +  }
Should be calling `viewSwap` utilizing your `data.view`

2023-09-28 17:25 UTC, shawnkost commented on js/main.js
> +  const views = document.querySelectorAll('.container.view');
This should be outside of `viewSwap`. You don't want to do `querySelector`s inside of functions, because you're forcing us to traverse the DOM tree every single time this function gets called

2023-09-28 18:37 UTC, omidzed commented
https://github.com/omidzed/code-journal/assets/136918229/395db7b6-6917-4c67-be81-41bb831f2505


https://github.com/omidzed/code-journal/assets/136918229/c93ccc61-300a-423a-a44d-c9df38a0c91a

2023-09-28 18:53 UTC, shawnkost approved these changes
👍🏻

2023-09-28 18:56 UTC, merged